# fly.toml app configuration file generated for turingroulette-polished-paper-1053 on 2025-10-17T14:19:34+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'turingroulette-polished-paper-1053'
primary_region = 'lhr'

[build]
  dockerfile = 'Dockerfile'

[env]
  DATA_DIR = '/app/data/'

[[mounts]]
  source = 'turingroulette_data'
  destination = '/app/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
